import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;
import java.util.ArrayList;
import java.util.HashMap;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author patrickkreek
 */
public class SetOmradeschef extends javax.swing.JFrame {
    
    private InfDB idb;
    
    /**
     * Creates new form SetOmradeschef
     */
    public SetOmradeschef(InfDB idb) {
        this.idb = idb;
        initComponents();
        fillCmbAgent();
        fillCmbOmrade();
        fillTxtAInfo();
        fillTxtOmrade();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LblRubrik = new javax.swing.JLabel();
        lblAgent = new javax.swing.JLabel();
        lblOmrade = new javax.swing.JLabel();
        btnAndra = new javax.swing.JButton();
        btnAvbryt = new javax.swing.JButton();
        cmbAgent = new javax.swing.JComboBox<>();
        cmbOmrade = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaInfo = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtaOmrade = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(33, 31, 31));

        jPanel1.setBackground(new java.awt.Color(33, 31, 31));

        LblRubrik.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        LblRubrik.setForeground(new java.awt.Color(255, 255, 255));
        LblRubrik.setText("Ändra områdeschef");

        lblAgent.setForeground(new java.awt.Color(153, 153, 153));
        lblAgent.setText("Agent");

        lblOmrade.setForeground(new java.awt.Color(153, 153, 153));
        lblOmrade.setText("Område");

        btnAndra.setBackground(new java.awt.Color(255, 255, 255));
        btnAndra.setForeground(new java.awt.Color(0, 0, 0));
        btnAndra.setText("Ändra");
        btnAndra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAndraActionPerformed(evt);
            }
        });

        btnAvbryt.setBackground(new java.awt.Color(255, 255, 255));
        btnAvbryt.setForeground(new java.awt.Color(0, 0, 0));
        btnAvbryt.setText("Avbryt");
        btnAvbryt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvbrytActionPerformed(evt);
            }
        });

        txtaInfo.setColumns(20);
        txtaInfo.setRows(5);
        jScrollPane1.setViewportView(txtaInfo);

        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Agenter");

        txtaOmrade.setColumns(20);
        txtaOmrade.setRows(5);
        jScrollPane2.setViewportView(txtaOmrade);

        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Områden");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAgent)
                            .addComponent(cmbAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAvbryt)
                            .addComponent(btnAndra))
                        .addGap(56, 56, 56))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(162, 162, 162)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbOmrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblOmrade)))
                            .addComponent(jLabel2))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LblRubrik)
                .addGap(267, 267, 267))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(LblRubrik)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAgent)
                    .addComponent(lblOmrade))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbOmrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAndra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAvbryt)
                        .addGap(40, 40, 40))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addGap(29, 29, 29))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAvbrytActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvbrytActionPerformed
        //Stänger ner rutan. 
        dispose();
    }//GEN-LAST:event_btnAvbrytActionPerformed

    private void btnAndraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAndraActionPerformed
        //Ändrar områdeschef
        String valdAgent = cmbAgent.getSelectedItem().toString();
        String valtOmrade = cmbOmrade.getSelectedItem().toString();
        
        try{
            if(valdAgent != null && valtOmrade != null){
                int agentID = Integer.parseInt(idb.fetchSingle("Select Agent_ID from Agent where Namn = '" + valdAgent + "'"));
                int omradeID = Integer.parseInt(idb.fetchSingle("Select Omrade.Omrades_ID from Omrade where Omrade.Benamning = '" + valtOmrade + "'"));
                idb.update("Update Omradeschef set Omradeschef.Agent_ID = '" + agentID + "'" + "Where Omrade = '" + omradeID + "'");
                System.out.println("Områdeschef har uppdaterats. ");
                JOptionPane.showMessageDialog(null, valdAgent + " Är nu områdeschef för område: " + valtOmrade);
                txtaOmrade.setText("");
                fillTxtOmrade();
                }
            
            }   
            catch (InfException err){
            JOptionPane.showMessageDialog(null, valtOmrade + " har redan en områdeschef!");
            System.out.println("Internt felmeddelande" + err.getMessage());
        }
        
    }
    private void fillCmbAgent(){
        //Fyller agent comboboxen
        String query = "Select namn from agent";
        ArrayList<String> allAgentNames;
        try{
            allAgentNames = idb.fetchColumn(query);
            
            for(String names : allAgentNames){
                cmbAgent.addItem(names);
                
            }
        }    
        catch (InfException err){
            JOptionPane.showMessageDialog(null, "Databasfel!");
            System.out.println("Internt felmeddelande" + err.getMessage());
        }
    }//GEN-LAST:event_btnAndraActionPerformed

    private void fillCmbOmrade(){
        //Fyller område comboboxen
        String query1 = "SELECT Omrade.Benamning FROM Omrade";
        ArrayList<String> allAreas;
        try{
            allAreas = idb.fetchColumn(query1);
            
            for(String areas : allAreas){
                cmbOmrade.addItem(areas);
            }
        }
        catch (InfException err){
            JOptionPane.showMessageDialog(null, "Databasfel!");
            System.out.println("Internt felmeddelande" + err.getMessage());
        }
    }
    
    private void fillTxtAInfo(){
        //Fyller textarean med information om alla agenter som finns. 
        txtaInfo.append("Agent_ID" + "\t");
        txtaInfo.append("Namn" + "\t");
        txtaInfo.append("Telefon" + "\n");
        
        ArrayList<HashMap<String, String>> agentInfo;
        
        try {
        String query2 = "SELECT Agent.Agent_ID, Agent.Namn, agent.Telefon from Agent";
        agentInfo = idb.fetchRows(query2);
        
        for(HashMap<String, String> aI : agentInfo){
            txtaInfo.append(aI.get("Agent_ID") + "\t");
            txtaInfo.append(aI.get("Namn") + "\t");
            txtaInfo.append(aI.get("Telefon") + "\n");
            }
        } catch (InfException err){
            JOptionPane.showMessageDialog(null, "Databasfel!");
            System.out.println("Internt felmeddelande" + err.getMessage());
        
        }
    }
    
    private void fillTxtOmrade(){
        //Fyller textarean med information om alla agenter som finns. 
        txtaOmrade.append("Agent_ID" + "\t");
        txtaOmrade.append("Omrade" + "\t");
        txtaOmrade.append("Benamning" + "\n");
        
        ArrayList<HashMap<String, String>> omradeInfo;
        
        try {
        String query3 = "SELECT Omradeschef.Agent_ID, Omradeschef.Omrade, Omrade.Benamning from Omradeschef join Omrade on Omradeschef.Omrade = Omrade.Omrades_ID";
        omradeInfo = idb.fetchRows(query3);
        
        for(HashMap<String, String> oI : omradeInfo){
            txtaOmrade.append(oI.get("Agent_ID") + "\t");
            txtaOmrade.append(oI.get("Omrade") + "\t");
            txtaOmrade.append(oI.get("Benamning") + "\n");
            }
        } catch (InfException err){
            JOptionPane.showMessageDialog(null, "Databasfel!");
            System.out.println("Internt felmeddelande" + err.getMessage());
        
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SetOmradeschef.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SetOmradeschef.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SetOmradeschef.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SetOmradeschef.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblRubrik;
    private javax.swing.JButton btnAndra;
    private javax.swing.JButton btnAvbryt;
    private javax.swing.JComboBox<String> cmbAgent;
    private javax.swing.JComboBox<String> cmbOmrade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAgent;
    private javax.swing.JLabel lblOmrade;
    private javax.swing.JTextArea txtaInfo;
    private javax.swing.JTextArea txtaOmrade;
    // End of variables declaration//GEN-END:variables
}
