
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author noahjarvback
 */
public class ÄndraInformationAgent extends javax.swing.JFrame {

    private static InfDB idb;

    /**
     * Creates new form ÄndraInformationAgent
     */
    public ÄndraInformationAgent(InfDB idb) throws InfException {
        initComponents();
        this.idb = idb;
        fillComboBoxOmrade();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblRubrik = new javax.swing.JLabel();
        txtAngeAgent = new javax.swing.JTextField();
        txtAgentNamn = new javax.swing.JTextField();
        txtAnstDatum = new javax.swing.JTextField();
        txtLosen = new javax.swing.JTextField();
        txtTelefon = new javax.swing.JTextField();
        cbxOmrade = new javax.swing.JComboBox<>();
        cbxAdmin = new javax.swing.JComboBox<>();
        lblAgentNamn = new javax.swing.JLabel();
        lblAnstDatum = new javax.swing.JLabel();
        lblLosen = new javax.swing.JLabel();
        lblTelefon = new javax.swing.JLabel();
        lblOmrade = new javax.swing.JLabel();
        lblAdmin = new javax.swing.JLabel();
        btnSokAgent = new javax.swing.JButton();
        btnAndra = new javax.swing.JButton();
        btnAvbryt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaLista = new javax.swing.JTextArea();
        lblAngeNamn = new javax.swing.JLabel();
        lblFyllVarde = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(33, 31, 31));

        lblRubrik.setFont(new java.awt.Font("Apple SD Gothic Neo", 1, 24)); // NOI18N
        lblRubrik.setForeground(new java.awt.Color(255, 255, 255));
        lblRubrik.setText("Ändra information om en agent");

        txtAngeAgent.setBackground(new java.awt.Color(255, 255, 255));
        txtAngeAgent.setForeground(new java.awt.Color(0, 0, 0));

        txtAgentNamn.setBackground(new java.awt.Color(255, 255, 255));
        txtAgentNamn.setForeground(new java.awt.Color(0, 0, 0));
        txtAgentNamn.setPreferredSize(new java.awt.Dimension(95, 30));

        txtAnstDatum.setBackground(new java.awt.Color(255, 255, 255));
        txtAnstDatum.setForeground(new java.awt.Color(0, 0, 0));
        txtAnstDatum.setText("YYYY-MM-DD");
        txtAnstDatum.setPreferredSize(new java.awt.Dimension(80, 30));

        txtLosen.setBackground(new java.awt.Color(255, 255, 255));
        txtLosen.setForeground(new java.awt.Color(0, 0, 0));
        txtLosen.setPreferredSize(new java.awt.Dimension(80, 30));

        txtTelefon.setBackground(new java.awt.Color(255, 255, 255));
        txtTelefon.setForeground(new java.awt.Color(0, 0, 0));
        txtTelefon.setPreferredSize(new java.awt.Dimension(80, 30));

        cbxOmrade.setBackground(new java.awt.Color(255, 255, 255));
        cbxOmrade.setForeground(new java.awt.Color(0, 0, 0));
        cbxOmrade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Välj område:" }));
        cbxOmrade.setPreferredSize(new java.awt.Dimension(72, 30));

        cbxAdmin.setBackground(new java.awt.Color(255, 255, 255));
        cbxAdmin.setForeground(new java.awt.Color(0, 0, 0));
        cbxAdmin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Välj admin:", "J", "N" }));
        cbxAdmin.setSize(new java.awt.Dimension(72, 30));

        lblAgentNamn.setForeground(new java.awt.Color(153, 153, 153));
        lblAgentNamn.setText("Agentens namn:");

        lblAnstDatum.setForeground(new java.awt.Color(153, 153, 153));
        lblAnstDatum.setText("Anställningsdatum:");

        lblLosen.setForeground(new java.awt.Color(153, 153, 153));
        lblLosen.setText("Lösenord:");

        lblTelefon.setForeground(new java.awt.Color(153, 153, 153));
        lblTelefon.setText("Telefonnummer:");

        lblOmrade.setForeground(new java.awt.Color(153, 153, 153));
        lblOmrade.setText("Område:");

        lblAdmin.setForeground(new java.awt.Color(153, 153, 153));
        lblAdmin.setText("Admin:");

        btnSokAgent.setBackground(new java.awt.Color(255, 255, 255));
        btnSokAgent.setForeground(new java.awt.Color(0, 0, 0));
        btnSokAgent.setText("Sök");
        btnSokAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSokAgentActionPerformed(evt);
            }
        });

        btnAndra.setBackground(new java.awt.Color(255, 255, 255));
        btnAndra.setForeground(new java.awt.Color(0, 0, 0));
        btnAndra.setText("Ändra");
        btnAndra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAndraActionPerformed(evt);
            }
        });

        btnAvbryt.setBackground(new java.awt.Color(255, 255, 255));
        btnAvbryt.setForeground(new java.awt.Color(0, 0, 0));
        btnAvbryt.setText("Avbryt");
        btnAvbryt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvbrytActionPerformed(evt);
            }
        });

        txtAreaLista.setBackground(new java.awt.Color(255, 255, 255));
        txtAreaLista.setColumns(20);
        txtAreaLista.setRows(5);
        jScrollPane1.setViewportView(txtAreaLista);

        lblAngeNamn.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lblAngeNamn.setForeground(new java.awt.Color(153, 153, 153));
        lblAngeNamn.setText("Ange namn på den agent du vill byta:");

        lblFyllVarde.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lblFyllVarde.setForeground(new java.awt.Color(153, 153, 153));
        lblFyllVarde.setText("Fyll i alla fält:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAgentNamn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAndra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtAngeAgent)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAgentNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbxOmrade, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblOmrade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(btnSokAgent))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAvbryt)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblAnstDatum)
                                            .addComponent(txtAnstDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtLosen, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblLosen))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTelefon)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbxAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(lblAdmin)))))
                        .addGap(70, 70, 70))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAngeNamn)
                            .addComponent(lblFyllVarde)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRubrik))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lblRubrik)
                .addGap(30, 30, 30)
                .addComponent(lblAngeNamn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAngeAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSokAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblFyllVarde)
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAgentNamn)
                    .addComponent(lblAnstDatum)
                    .addComponent(lblLosen)
                    .addComponent(lblTelefon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAgentNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAnstDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAdmin)
                    .addComponent(lblOmrade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxOmrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAndra)
                    .addComponent(btnAvbryt))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean okFunktion() {
        boolean ok = true;
        if (Validering.kollaDatumCheck(txtAnstDatum.getText()) == false) {
            ok = false;
        }
        else if (Validering.arTom(txtAgentNamn) == true) {
            ok = false;
        }
        else if (Validering.langLosen(txtLosen) == true) {
            ok = false;
        }
        else if (Validering.arTom(txtLosen) == true) {
            ok = false;
        }
        else if (Validering.arTom(txtTelefon) == true) {
            ok = false;
        }
        if (Validering.comboBox(cbxOmrade) == true) {
            ok = false;
            JOptionPane.showMessageDialog(null, "Välj ett av de alternativ från område som finns");
        }
        if (Validering.comboBox(cbxAdmin) == true) {
            ok = false;
            JOptionPane.showMessageDialog(null, "Välj ett av de alternativ från admin som finns");
        }
        return ok;
    }

    private void fillComboBoxOmrade() throws InfException {
        String query = "SELECT BENAMNING FROM OMRADE";
        ArrayList<String> omrade = idb.fetchColumn(query);
        for (String ettOmrade : omrade) {
            cbxOmrade.addItem(ettOmrade);
        }
    }

    private void sokAgent() {

        String agentNamn = txtAngeAgent.getText();

        try {
            HashMap<String, String> agentLista = idb.fetchRow("SELECT NAMN, TELEFON, ANSTALLNINGSDATUM, ADMINISTRATOR, LOSENORD, BENAMNING FROM AGENT"
                    + " JOIN OMRADE ON OMRADES_ID = OMRADE "
                    + " WHERE NAMN = '" + agentNamn + "'");
            System.out.println(agentLista);
            agentNamn = agentLista.get("NAMN");

            if (agentNamn == null) {
                JOptionPane.showMessageDialog(null, "Agenten finns inte");
                txtAgentNamn.setText("");
                txtAnstDatum.setText("YYYY-MM-DD");
                txtLosen.setText("");
                txtTelefon.setText("");
                cbxAdmin.setSelectedItem("Välj admin:");
                cbxOmrade.setSelectedItem("Välj område:");
                txtAreaLista.setText("");
            } else {

                txtAgentNamn.setText(agentLista.get("NAMN"));
                txtAnstDatum.setText(agentLista.get("ANSTALLNINGSDATUM"));
                txtLosen.setText(agentLista.get("LOSENORD"));
                txtTelefon.setText(agentLista.get("TELEFON"));
                cbxAdmin.setSelectedItem(agentLista.get("ADMINISTRATOR"));
                cbxOmrade.setSelectedItem(agentLista.get("BENAMNING"));

                txtAreaLista.setText("");
                txtAreaLista.append("Namn:  " + agentLista.get("NAMN") + "\n");
                txtAreaLista.append("Anställningsdatum:  " + agentLista.get("ANSTALLNINGSDATUM") + "\n");
                txtAreaLista.append("Lösenord:  " + agentLista.get("LOSENORD") + "\n");
                txtAreaLista.append("Telefonnummer:  " + agentLista.get("TELEFON") + "\n");
                txtAreaLista.append("Administratör:  " + agentLista.get("ADMINISTRATOR") + "\n");
                txtAreaLista.append("Område:  " + agentLista.get("BENAMNING") + "\n");

            }
        } catch (InfException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

    }
    private void btnSokAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSokAgentActionPerformed
        // TODO add your handling code here:
        sokAgent();


    }//GEN-LAST:event_btnSokAgentActionPerformed

    private void btnAndraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAndraActionPerformed
        // TODO add your handling code here:
        if (okFunktion() == true) {
            String agentNamn = txtAngeAgent.getText();
            String agentNytt = txtAgentNamn.getText();
            String datum = txtAnstDatum.getText();
            String losen = txtLosen.getText();
            String telefonNr = txtTelefon.getText();
            String omrade = cbxOmrade.getSelectedItem().toString();
            String admin = cbxAdmin.getSelectedItem().toString();

            try {
                idb.update("UPDATE AGENT SET ANSTALLNINGSDATUM = '" + datum + "'" + "WHERE NAMN = '" + agentNamn + "'");
                idb.update("UPDATE AGENT SET LOSENORD = '" + losen + "'" + "WHERE NAMN = '" + agentNamn + "'");
                idb.update("UPDATE AGENT SET TELEFON = '" + telefonNr + "'" + "WHERE NAMN = '" + agentNamn + "'");
                idb.update("UPDATE AGENT SET ADMINISTRATOR = '" + admin + "'" + "WHERE NAMN = '" + agentNamn + "'");
                int omradesID = Integer.parseInt(idb.fetchSingle("SELECT OMRADES_ID FROM OMRADE WHERE BENAMNING = '" + omrade + "'"));
                idb.update("UPDATE AGENT SET OMRADE = '" + omradesID + "'" + "WHERE NAMN = '" + agentNamn + "'");
                idb.update("UPDATE AGENT SET NAMN = '" + agentNytt + "'" + "WHERE NAMN = '" + agentNamn + "'");
                JOptionPane.showMessageDialog(null, "Agenten har uppdaterats");

                txtAngeAgent.setText(txtAgentNamn.getText());
            } catch (InfException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
            sokAgent();
        }

    }//GEN-LAST:event_btnAndraActionPerformed

    private void btnAvbrytActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvbrytActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnAvbrytActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ÄndraInformationAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ÄndraInformationAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ÄndraInformationAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ÄndraInformationAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ÄndraInformationAgent(idb).setVisible(true);
                } catch (InfException ex) {
                    Logger.getLogger(ÄndraInformationAgent.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAndra;
    private javax.swing.JButton btnAvbryt;
    private javax.swing.JButton btnSokAgent;
    private javax.swing.JComboBox<String> cbxAdmin;
    private javax.swing.JComboBox<String> cbxOmrade;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAdmin;
    private javax.swing.JLabel lblAgentNamn;
    private javax.swing.JLabel lblAngeNamn;
    private javax.swing.JLabel lblAnstDatum;
    private javax.swing.JLabel lblFyllVarde;
    private javax.swing.JLabel lblLosen;
    private javax.swing.JLabel lblOmrade;
    private javax.swing.JLabel lblRubrik;
    private javax.swing.JLabel lblTelefon;
    private javax.swing.JTextField txtAgentNamn;
    private javax.swing.JTextField txtAngeAgent;
    private javax.swing.JTextField txtAnstDatum;
    private javax.swing.JTextArea txtAreaLista;
    private javax.swing.JTextField txtLosen;
    private javax.swing.JTextField txtTelefon;
    // End of variables declaration//GEN-END:variables
}
